wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685478122.547647
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
